apiVersion: v1
kind: Secret
metadata:
  name: sentinela-secrets
  labels:
    {{- include "sentinela.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgresql://sentinela:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/sentinela"
  jwt-secret: {{ .Values.apiGateway.env.JWT_SECRET | quote }}
  minio-access-key: {{ .Values.minio.auth.rootUser | quote }}
  minio-secret-key: {{ .Values.minio.auth.rootPassword | quote }}
